version: '3.8'

services:
  # Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_api
    environment:
      SAVED_MODEL_PATH: "/app/Model/Saved/dogxcat.pth"
      SERVER_HOST: 127.0.0.1
      SERVER_PORT: 8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    network_mode: "host"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=localhost
        - VITE_API_PORT=8000
    container_name: frontend_api
    # depends_on:
    #   condition: service_healthy
    ports:
      - "3000:3000"
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

# networks:
#   application-network:
#     driver: bridge

    # public_network:
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: 172.20.0.0/16

volumes:
  backend_data:
    driver: local
  backend_logs:
    driver: local